apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: your-app
  template:
    metadata:
      labels:
        app: your-app
    spec:
      containers:
        - name: your-app
          image: chantim/gcr.io-k8s-minikube-kicbase:v0.0.44
          ports:
            - containerPort: 3000

