name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: docker build . -t chantim/gcr.io-k8s-minikube-kicbase:v0.0.44

      # Add more steps for testing, linting, etc.
      # praciticng rebasing, adding random line comment
      # this was made on a practice branch for submitting a pull request

      - name: Load Docker Image into Minikube
        run: |
          eval $(minikube docker-env)
          docker save chantim/gcr.io-k8s-minikube-kicbase:v0.0.44 > image.tar
          docker load < image.tar

